In [24]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plot
import numpy as np

In [25]:
df = pd.read_csv('customer.csv')

In [26]:
df.sample(5)

    age  gender review education purchased
22   18  Female   Poor        PG       Yes
12   51    Male   Poor    School        No
18   19    Male   Good    School        No
10   98  Female   Good        UG       Yes
49   25  Female   Good        UG        No

In [27]:
df = df.iloc[:,2:]

In [28]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [30]:
from sklearn.preprocessing import OrdinalEncoder

In [31]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [37]:
x_train

     review education
26     Poor        PG
16     Poor        UG
20  Average    School
35     Poor    School
15     Poor        UG
32  Average        UG
9      Good        UG
48     Good        UG
12     Poor    School
39     Poor        PG
7      Poor    School
41     Good        PG
36     Good        UG
1      Poor        UG
34  Average    School
42     Good        PG
29  Average        UG
43     Poor        PG
17     Poor        UG
4   Average        UG
30  Average        UG
25     Good    School
10     Good        UG
0   Average    School
44  Average        UG
18     Good    School
2      Good        PG
45     Poor        PG
13  Average    School
40     Good    School
19     Poor        PG
27     Poor        PG
6      Good    School
33     Good        PG
3      Good        PG
31     Poor    School
38     Good    School
47     Good        PG
24  Average        PG
11     Good        UG

In [32]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [36]:
x_train_transformed = oe.transform(x_train)
x_test_transformed = oe.transform(x_test)
print("Transformed x_train:", x_train_transformed)
print("Transformed x_test:", x_test_transformed)

Transformed x_train: [[0. 2.]
 [0. 1.]
 [1. 0.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [2. 1.]
 [2. 1.]
 [0. 0.]
 [0. 2.]
 [0. 0.]
 [2. 2.]
 [2. 1.]
 [0. 1.]
 [1. 0.]
 [2. 2.]
 [1. 1.]
 [0. 2.]
 [0. 1.]
 [1. 1.]
 [1. 1.]
 [2. 0.]
 [2. 1.]
 [1. 0.]
 [1. 1.]
 [2. 0.]
 [2. 2.]
 [0. 2.]
 [1. 0.]
 [2. 0.]
 [0. 2.]
 [0. 2.]
 [2. 0.]
 [2. 2.]
 [2. 2.]
 [0. 0.]
 [2. 0.]
 [2. 2.]
 [1. 2.]
 [2. 1.]]
Transformed x_test: [[1. 2.]
 [1. 0.]
 [0. 2.]
 [0. 2.]
 [2. 0.]
 [0. 2.]
 [0. 0.]
 [1. 1.]
 [2. 1.]
 [1. 2.]]

In [38]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [39]:
from sklearn.preprocessing import LabelEncoder

In [40]:
le = LabelEncoder()

In [41]:
le.fit(y_train)

LabelEncoder()

In [42]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [43]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [44]:
y_train

array([0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1])

In [46]:
import pandas as pd 
import numpy as np

In [47]:
df = pd.read_csv('cars.csv')

In [48]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [63]:
df.sample(10)

        brand  km_driven    fuel         owner  selling_price
5382   Maruti      75000  Diesel  Second Owner         631000
2590   Nissan      90000  Diesel   First Owner         300000
6118   Maruti      23000  Petrol   First Owner         515000
5880  Hyundai     110000  Petrol  Second Owner         110000
2544   Maruti     120000  Diesel   First Owner         320000
4604   Maruti     110000  Petrol   Third Owner         204000
3619     Tata     110000  Diesel   First Owner         275000
6595  Hyundai       5000  Petrol   First Owner         500000
5494  Hyundai      80000  Petrol  Second Owner         129000
3581   Maruti      40000  Diesel   First Owner         754000

In [65]:
df['brand'].nunique()

32

In [68]:
df['selling_price'].value_counts()

selling_price
300000     227
600000     213
350000     209
550000     204
450000     195
          ...
308000       1
3900000      1
2850000      1
39000        1
746000       1
Name: count, Length: 677, dtype: int64

#ONE HOT ENCODING USING PANDAS

In [69]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [70]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first = True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

ONE HOT ENCODING USING SKLEARN

In [73]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state= 2)

In [74]:
x_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [75]:
x_test.head()

         brand  km_driven    fuel         owner
606    Hyundai      80000  Petrol   First Owner
7575  Mahindra      70000  Diesel  Second Owner
7705    Toyota      68089  Petrol   First Owner
4305   Hyundai      70000  Petrol  Second Owner
2685  Mahindra      97000  Diesel  Second Owner

In [76]:
from sklearn.preprocessing import OneHotEncoder

In [77]:
ohe = OneHotEncoder()

In [80]:
x_train_new = ohe.fit_transform(x_train[['fuel','owner']]).toarray()

In [81]:
x_test_new = ohe.transform(x_test[['fuel','owner']]).toarray()

In [82]:
x_train_new

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [85]:
np.hstack ((x_train[['brand','km_driven']].values,x_train_new)).shape

(6502, 11)

In [87]:
counts = df['brand'].value_counts()

In [88]:
df['brand'].nunique()
threshold = 100

In [90]:
repl = counts[counts<=threshold].index

In [92]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(10)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
299,False,False,False,False,True,False,False,False,False,False,False,False,False
5048,False,False,False,False,False,False,True,False,False,False,False,False,False
7954,False,False,False,False,False,False,True,False,False,False,False,False,False
2470,False,False,True,False,False,False,False,False,False,False,False,False,False
1369,False,False,False,False,False,True,False,False,False,False,False,False,False
5999,False,False,False,False,False,False,False,False,False,True,False,False,False
5447,False,False,False,False,False,False,True,False,False,False,False,False,False
6652,False,False,False,False,False,False,True,False,False,False,False,False,False
797,False,False,False,False,False,False,False,False,False,False,False,False,True
291,False,False,False,False,True,False,False,False,False,False,False,False,False